package com.kauniv.lightrip.global.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum District {

    // 서울특별시 (25개 구)
    JONGNO("종로구"),
    JUNG("중구"),
    YONGSAN("용산구"),
    SEONGDONG("성동구"),
    GWANGJIN("광진구"),
    DONGDAEMUN("동대문구"),
    JUNGNANG("중랑구"),
    SEONGBUK("성북구"),
    GANGBUK("강북구"),
    DOBONG("도봉구"),
    NOWON("노원구"),
    EUNPYEONG("은평구"),
    SEODAEMUN("서대문구"),
    MAPO("마포구"),
    YANGCHEON("양천구"),
    GANGSEO("강서구"),
    GURO("구로구"),
    GEUMCHEON("금천구"),
    YEONGDEUNGPO("영등포구"),
    DONGJAK("동작구"),
    GWANAK("관악구"),
    SEOCHO("서초구"),
    GANGNAM("강남구"),
    SONGPA("송파구"),
    GANGDONG("강동구"),

    // 부산광역시 (15구 1군)
    BUSAN_JUNG("부산 중구"),
    BUSAN_SEO("부산 서구"),
    BUSAN_DONG("부산 동구"),
    BUSAN_YEONGDO("부산 영도구"),
    BUSAN_BUSANJIN("부산 부산진구"),
    BUSAN_DONGNAE("부산 동래구"),
    BUSAN_NAM("부산 남구"),
    BUSAN_BUK("부산 북구"),
    BUSAN_HAEUNDAE("부산 해운대구"),
    BUSAN_SAHA("부산 사하구"),
    BUSAN_GEUMJEONG("부산 금정구"),
    BUSAN_GANGSEO("부산 강서구"),
    BUSAN_YEONJE("부산 연제구"),
    BUSAN_SUYEONG("부산 수영구"),
    BUSAN_SASANG("부산 사상구"),
    BUSAN_GIJANG("부산 기장군"),

    // 대구광역시 (7구 2군)
    DAEGU_JUNG("대구 중구"),
    DAEGU_DONG("대구 동구"),
    DAEGU_SEO("대구 서구"),
    DAEGU_NAM("대구 남구"),
    DAEGU_BUK("대구 북구"),
    DAEGU_SUSEONG("대구 수성구"),
    DAEGU_DALSEO("대구 달서구"),
    DAEGU_DALSEONG("대구 달성군"),
    DAEGU_GUNWI("대구 군위군"),

    // 인천광역시 (8구 2군)
    INCHEON_JUNG("인천 중구"),
    INCHEON_DONG("인천 동구"),
    INCHEON_MICHUHOL("인천 미추홀구"),
    INCHEON_YEONSU("인천 연수구"),
    INCHEON_NAMDONG("인천 남동구"),
    INCHEON_BUPYEONG("인천 부평구"),
    INCHEON_GYEYANG("인천 계양구"),
    INCHEON_SEO("인천 서구"),
    INCHEON_GANGHWA("인천 강화군"),
    INCHEON_ONGJIN("인천 옹진군"),

    // 광주광역시 (5구)
    GWANGJU_DONG("광주 동구"),
    GWANGJU_SEO("광주 서구"),
    GWANGJU_NAM("광주 남구"),
    GWANGJU_BUK("광주 북구"),
    GWANGJU_GWANGSAN("광주 광산구"),

    // 대전광역시 (5구)
    DAEJEON_DONG("대전 동구"),
    DAEJEON_JUNG("대전 중구"),
    DAEJEON_SEO("대전 서구"),
    DAEJEON_YUSEONG("대전 유성구"),
    DAEJEON_DAEDEOK("대전 대덕구"),

    // 울산광역시 (4구 1군)
    ULSAN_JUNG("울산 중구"),
    ULSAN_NAM("울산 남구"),
    ULSAN_DONG("울산 동구"),
    ULSAN_BUK("울산 북구"),
    ULSAN_ULJU("울산 울주군"),

    // 세종특별자치시
    SEJONG("세종특별자치시"),

    // 경기도 — 구가 있는 시는 구 단위
    // 수원시
    SUWON_JANGAN("수원 장안구"),
    SUWON_GWONSEON("수원 권선구"),
    SUWON_PALDAL("수원 팔달구"),
    SUWON_YEONGTONG("수원 영통구"),
    // 성남시
    SEONGNAM_SUJEONG("성남 수정구"),
    SEONGNAM_JUNGWON("성남 중원구"),
    SEONGNAM_BUNDANG("성남 분당구"),
    // 고양시
    GOYANG_DEOKYANG("고양 덕양구"),
    GOYANG_ILSANDONG("고양 일산동구"),
    GOYANG_ILSANSEO("고양 일산서구"),
    // 용인시
    YONGIN_CHEOIN("용인 처인구"),
    YONGIN_GIHEUNG("용인 기흥구"),
    YONGIN_SUJI("용인 수지구"),
    // 부천시
    BUCHEON_WONMI("부천 원미구"),
    BUCHEON_SOSA("부천 소사구"),
    BUCHEON_OJEONG("부천 오정구"),
    // 안산시
    ANSAN_SANGNOK("안산 상록구"),
    ANSAN_DANWON("안산 단원구"),
    // 안양시
    ANYANG_MANAN("안양 만안구"),
    ANYANG_DONGAN("안양 동안구"),
    // 화성시 (2026.2 구 신설)
    HWASEONG_MANSE("화성 만세구"),
    HWASEONG_HYOHAENG("화성 효행구"),
    HWASEONG_BYEONGJEOM("화성 병점구"),
    HWASEONG_DONGTAN("화성 동탄구"),
    // 경기도 — 구가 없는 시·군
    NAMYANGJU("남양주시"),
    PYEONGTAEK("평택시"),
    UIJEONGBU("의정부시"),
    SIHEUNG("시흥시"),
    PAJU("파주시"),
    GIMPO("김포시"),
    GWANGMYEONG("광명시"),
    GWANGJU_GG("광주시"),
    GUNPO("군포시"),
    HANAM("하남시"),
    OSAN("오산시"),
    ICHEON("이천시"),
    YANGJU("양주시"),
    ANSEONG("안성시"),
    GURI("구리시"),
    POCHEON("포천시"),
    UIWANG("의왕시"),
    YEOJU("여주시"),
    DONGDUCHEON("동두천시"),
    GAPYEONG("가평군"),
    YANGPYEONG("양평군"),
    YEONCHEON("연천군"),
    GWACHEON("과천시"),

    // 강원특별자치도 (7시 11군)
    CHUNCHEON("춘천시"),
    WONJU("원주시"),
    GANGNEUNG("강릉시"),
    DONGHAE("동해시"),
    TAEBAEK("태백시"),
    SOKCHO("속초시"),
    SAMCHEOK("삼척시"),
    HONGCHEON("홍천군"),
    HOENGSEONG("횡성군"),
    YEONGWOL("영월군"),
    PYEONGCHANG("평창군"),
    JEONGSEON("정선군"),
    CHEORWON("철원군"),
    HWACHEON("화천군"),
    YANGGU("양구군"),
    INJE("인제군"),
    GOSEONG_GW("강원 고성군"),
    YANGYANG("양양군"),

    // 충청북도 (3시 8군)
    CHEONGJU("청주시"),
    CHUNGJU("충주시"),
    JECHEON("제천시"),
    BOEUN("보은군"),
    OKCHEON("옥천군"),
    YEONGDONG("영동군"),
    JEUNGPYEONG("증평군"),
    JINCHEON("진천군"),
    GOESAN("괴산군"),
    EUMSEONG("음성군"),
    DANYANG("단양군"),

    // 충청남도 (8시 7군)
    CHEONAN("천안시"),
    GONGJU("공주시"),
    BORYEONG("보령시"),
    ASAN("아산시"),
    SEOSAN("서산시"),
    NONSAN("논산시"),
    GYERYONG("계룡시"),
    DANGJIN("당진시"),
    GEUMSAN("금산군"),
    BUYEO("부여군"),
    SEOCHEON("서천군"),
    CHEONGYANG("청양군"),
    HONGSEONG("홍성군"),
    YESAN("예산군"),
    TAEAN("태안군"),

    // 전북특별자치도 (6시 8군)
    JEONJU("전주시"),
    GUNSAN("군산시"),
    IKSAN("익산시"),
    JEONGEUP("정읍시"),
    NAMWON("남원시"),
    GIMJE("김제시"),
    WANJU("완주군"),
    JINAN("진안군"),
    MUJU("무주군"),
    JANGSU("장수군"),
    IMSIL("임실군"),
    SUNCHANG("순창군"),
    GOCHANG("고창군"),
    BUAN("부안군"),

    // 전라남도 (5시 17군)
    MOKPO("목포시"),
    YEOSU("여수시"),
    SUNCHEON("순천시"),
    NAJU("나주시"),
    GWANGYANG("광양시"),
    DAMYANG("담양군"),
    GOKSEONG("곡성군"),
    GURYE("구례군"),
    GOHEUNG("고흥군"),
    BOSEONG("보성군"),
    HWASUN("화순군"),
    JANGHEUNG("장흥군"),
    GANGJIN("강진군"),
    HAENAM("해남군"),
    YEONGAM("영암군"),
    MUAN("무안군"),
    HAMPYEONG("함평군"),
    YEONGGWANG("영광군"),
    JANGSEONG("장성군"),
    WANDO("완도군"),
    JINDO("진도군"),
    SINAN("신안군"),

    // 경상북도 (10시 12군)
    POHANG("포항시"),
    GYEONGJU("경주시"),
    GIMCHEON("김천시"),
    ANDONG("안동시"),
    GUMI("구미시"),
    YEONGJU("영주시"),
    YEONGCHEON("영천시"),
    SANGJU("상주시"),
    MUNGYEONG("문경시"),
    GYEONGSAN("경산시"),
    UISEONG("의성군"),
    CHEONGSONG("청송군"),
    YEONGYANG("영양군"),
    YEONGDEOK("영덕군"),
    CHEONGDO("청도군"),
    GORYEONG("고령군"),
    SEONGJU("성주군"),
    CHILGOK("칠곡군"),
    YECHEON("예천군"),
    BONGHWA("봉화군"),
    ULJIN("울진군"),
    ULLEUNG("울릉군"),

    // 경상남도 (8시 10군)
    CHANGWON("창원시"),
    JINJU("진주시"),
    TONGYEONG("통영시"),
    SACHEON("사천시"),
    GIMHAE("김해시"),
    MIRYANG("밀양시"),
    GEOJE("거제시"),
    YANGSAN("양산시"),
    UIRYEONG("의령군"),
    HAMAN("함안군"),
    CHANGNYEONG("창녕군"),
    GOSEONG_GN("경남 고성군"),
    NAMHAE("남해군"),
    HADONG("하동군"),
    SANCHEONG("산청군"),
    HAMYANG("함양군"),
    GEOCHANG("거창군"),
    HAPCHEON("합천군"),

    // 제주특별자치도 (2시)
    JEJU("제주시"),
    SEOGWIPO("서귀포시");

    private final String displayName;
}
