-- UGC 신고/차단 기능 (Issue #197)
-- App Store Guideline 1.2 / Google UGC 정책 대응:
--   1) 게시물 신고 + 서로 다른 신고자 누적 시 자동 숨김("24시간 내 조치" 요건)
--   2) 사용자 차단 (양방향 비노출 + 친구 관계 해제)

-- =============================================
-- 1. passport.status — 콘텐츠 노출 상태
--    ACTIVE(정상) / HIDDEN(신고 누적 자동 숨김) / DELETED(운영 삭제, 예약)
--    기존 행은 DEFAULT 로 전부 ACTIVE 백필
-- =============================================
ALTER TABLE public.passport
    ADD COLUMN status varchar(20) DEFAULT 'ACTIVE' NOT NULL;

ALTER TABLE public.passport
    ADD CONSTRAINT passport_status_check
        CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED'));

-- 피드/상세/불빛 조회에서 status = 'ACTIVE' 필터가 매번 붙으므로 인덱스
CREATE INDEX idx_passport_status ON public.passport (status);

-- =============================================
-- 2. passport_report — 게시물 신고
-- =============================================
CREATE TABLE public.passport_report (
    passport_report_id bigint NOT NULL,
    reporter_id        bigint NOT NULL,
    passport_id        bigint NOT NULL,
    reason             varchar(20) NOT NULL,
    detail             varchar(500),
    status             varchar(20) DEFAULT 'PENDING' NOT NULL,
    created_at         timestamp(6) without time zone,
    CONSTRAINT passport_report_reason_check
        CHECK (reason IN ('SPAM', 'ABUSE', 'SEXUAL', 'COPYRIGHT', 'FALSE_INFO', 'ETC')),
    CONSTRAINT passport_report_status_check
        CHECK (status IN ('PENDING', 'AUTO_HIDDEN', 'RESOLVED', 'REJECTED'))
);

ALTER TABLE public.passport_report ALTER COLUMN passport_report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passport_report_passport_report_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.passport_report
    ADD CONSTRAINT passport_report_pkey PRIMARY KEY (passport_report_id);

-- 한 사용자가 같은 게시물을 중복 신고할 수 없음
ALTER TABLE ONLY public.passport_report
    ADD CONSTRAINT uk_passport_report_reporter_passport UNIQUE (reporter_id, passport_id);

ALTER TABLE ONLY public.passport_report
    ADD CONSTRAINT fk_passport_report_reporter
        FOREIGN KEY (reporter_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.passport_report
    ADD CONSTRAINT fk_passport_report_passport
        FOREIGN KEY (passport_id) REFERENCES public.passport(passport_id) ON DELETE CASCADE;

-- 누적 신고자 수 COUNT / 운영자 상태별 목록 조회용
CREATE INDEX idx_passport_report_passport_id ON public.passport_report (passport_id);
CREATE INDEX idx_passport_report_status ON public.passport_report (status);

-- =============================================
-- 3. user_block — 사용자 차단
-- =============================================
CREATE TABLE public.user_block (
    user_block_id bigint NOT NULL,
    blocker_id    bigint NOT NULL,
    blocked_id    bigint NOT NULL,
    created_at    timestamp(6) without time zone
);

ALTER TABLE public.user_block ALTER COLUMN user_block_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_block_user_block_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT user_block_pkey PRIMARY KEY (user_block_id);

-- 같은 상대를 중복 차단할 수 없음
ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT uk_user_block_blocker_blocked UNIQUE (blocker_id, blocked_id);

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT fk_user_block_blocker
        FOREIGN KEY (blocker_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT fk_user_block_blocked
        FOREIGN KEY (blocked_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- "나를 차단한 사용자" 역방향 조회용 (피드/추천에서 매 요청 사용)
CREATE INDEX idx_user_block_blocked_id ON public.user_block (blocked_id);
