--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Extensions
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';

--
-- PostGIS: passport.location 자동 동기화 함수
--

CREATE FUNCTION public.update_passport_location() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.location = ST_SetSRID(ST_MakePoint(NEW.longitude::float, NEW.latitude::float), 4326);
    RETURN NEW;
END;
$$;

SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Tables
--

CREATE TABLE public.auth (
    auth_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    refresh_token text,
    social_id character varying(50) NOT NULL,
    social_type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT auth_social_type_check CHECK (((social_type)::text = ANY ((ARRAY['KAKAO'::character varying, 'GOOGLE'::character varying])::text[])))
);

ALTER TABLE public.auth ALTER COLUMN auth_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_auth_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.district_cover (
    cover_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    district_category character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    passport_image_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT district_cover_district_category_check CHECK (((district_category)::text = ANY ((ARRAY['JONGNO'::character varying, 'JUNG'::character varying, 'YONGSAN'::character varying, 'SEONGDONG'::character varying, 'GWANGJIN'::character varying, 'DONGDAEMUN'::character varying, 'JUNGNANG'::character varying, 'SEONGBUK'::character varying, 'GANGBUK'::character varying, 'DOBONG'::character varying, 'NOWON'::character varying, 'EUNPYEONG'::character varying, 'SEODAEMUN'::character varying, 'MAPO'::character varying, 'YANGCHEON'::character varying, 'GANGSEO'::character varying, 'GURO'::character varying, 'GEUMCHEON'::character varying, 'YEONGDEUNGPO'::character varying, 'DONGJAK'::character varying, 'GWANAK'::character varying, 'SEOCHO'::character varying, 'GANGNAM'::character varying, 'SONGPA'::character varying, 'GANGDONG'::character varying, 'SUWON'::character varying, 'SEONGNAM'::character varying, 'GOYANG'::character varying, 'YONGIN'::character varying, 'BUCHEON'::character varying, 'ANSAN'::character varying, 'ANYANG'::character varying, 'NAMYANGJU'::character varying, 'HWASEONG'::character varying, 'PYEONGTAEK'::character varying, 'UIJEONGBU'::character varying, 'SIHEUNG'::character varying, 'PAJU'::character varying, 'GIMPO'::character varying, 'GWANGMYEONG'::character varying, 'GWANGJU_GG'::character varying, 'GUNPO'::character varying, 'HANAM'::character varying, 'OSAN'::character varying, 'ICHEON'::character varying, 'YANGJU'::character varying, 'ANSEONG'::character varying, 'GURI'::character varying, 'POCHEON'::character varying, 'UIWANG'::character varying, 'YEOJU'::character varying, 'DONGDUCHEON'::character varying, 'GAPYEONG'::character varying, 'YANGPYEONG'::character varying, 'YEONCHEON'::character varying, 'GWACHEON'::character varying])::text[])))
);

ALTER TABLE public.district_cover ALTER COLUMN cover_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.district_cover_cover_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.friend (
    friend_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    receiver_id bigint NOT NULL,
    request_id bigint NOT NULL,
    CONSTRAINT friend_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying])::text[])))
);

ALTER TABLE public.friend ALTER COLUMN friend_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friend_friend_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.likes (
    like_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    passport_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.likes ALTER COLUMN like_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.likes_like_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.passport (
    passport_id bigint NOT NULL,
    address character varying(50) NOT NULL,
    category character varying(255) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    district character varying(50),
    district_category character varying(255) NOT NULL,
    latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL,
    music_artist character varying(100),
    music_title character varying(100),
    space_name character varying(50),
    updated_at timestamp(6) without time zone,
    visited_at date NOT NULL,
    user_id bigint NOT NULL,
    team_id bigint,
    visibility character varying(20) NOT NULL,
    scrap_count bigint DEFAULT 0 NOT NULL,
    like_count bigint DEFAULT 0 NOT NULL,
    ai_category character varying(20),
    draft text,
    location public.geometry(Point,4326),
    CONSTRAINT passport_ai_category_check CHECK (((ai_category)::text = ANY ((ARRAY['CAFE'::character varying, 'RESTAURANT'::character varying, 'BAR'::character varying, 'CULTURE'::character varying, 'ACTIVITY'::character varying, 'SHOPPING'::character varying, 'NATURE'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT passport_category_check CHECK (((category)::text = ANY ((ARRAY['CAFE'::character varying, 'RESTAURANT'::character varying, 'BAR'::character varying, 'TOURIST'::character varying, 'NATURE'::character varying, 'CULTURE'::character varying, 'ACTIVITY'::character varying, 'ACCOMMODATION'::character varying, 'SHOPPING'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT passport_district_category_check CHECK (((district_category)::text = ANY ((ARRAY['JONGNO'::character varying, 'JUNG'::character varying, 'YONGSAN'::character varying, 'SEONGDONG'::character varying, 'GWANGJIN'::character varying, 'DONGDAEMUN'::character varying, 'JUNGNANG'::character varying, 'SEONGBUK'::character varying, 'GANGBUK'::character varying, 'DOBONG'::character varying, 'NOWON'::character varying, 'EUNPYEONG'::character varying, 'SEODAEMUN'::character varying, 'MAPO'::character varying, 'YANGCHEON'::character varying, 'GANGSEO'::character varying, 'GURO'::character varying, 'GEUMCHEON'::character varying, 'YEONGDEUNGPO'::character varying, 'DONGJAK'::character varying, 'GWANAK'::character varying, 'SEOCHO'::character varying, 'GANGNAM'::character varying, 'SONGPA'::character varying, 'GANGDONG'::character varying, 'SUWON'::character varying, 'SEONGNAM'::character varying, 'GOYANG'::character varying, 'YONGIN'::character varying, 'BUCHEON'::character varying, 'ANSAN'::character varying, 'ANYANG'::character varying, 'NAMYANGJU'::character varying, 'HWASEONG'::character varying, 'PYEONGTAEK'::character varying, 'UIJEONGBU'::character varying, 'SIHEUNG'::character varying, 'PAJU'::character varying, 'GIMPO'::character varying, 'GWANGMYEONG'::character varying, 'GWANGJU_GG'::character varying, 'GUNPO'::character varying, 'HANAM'::character varying, 'OSAN'::character varying, 'ICHEON'::character varying, 'YANGJU'::character varying, 'ANSEONG'::character varying, 'GURI'::character varying, 'POCHEON'::character varying, 'UIWANG'::character varying, 'YEOJU'::character varying, 'DONGDUCHEON'::character varying, 'GAPYEONG'::character varying, 'YANGPYEONG'::character varying, 'YEONCHEON'::character varying, 'GWACHEON'::character varying])::text[]))),
    CONSTRAINT passport_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'FRIENDS_ONLY'::character varying])::text[])))
);

ALTER TABLE public.passport ALTER COLUMN passport_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passport_passport_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.passport_image (
    passport_image_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    image_order integer NOT NULL,
    image_url text NOT NULL,
    passport_id bigint NOT NULL
);

ALTER TABLE public.passport_image ALTER COLUMN passport_image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passport_image_passport_image_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.passport_stamp (
    passport_stamp_id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    image_url text NOT NULL,
    passport_id bigint NOT NULL,
    CONSTRAINT passport_stamp_category_check CHECK (((category)::text = ANY ((ARRAY['CAFE'::character varying, 'RESTAURANT'::character varying, 'BAR'::character varying, 'CULTURE'::character varying, 'ACTIVITY'::character varying, 'SHOPPING'::character varying, 'NATURE'::character varying, 'ETC'::character varying])::text[])))
);

ALTER TABLE public.passport_stamp ALTER COLUMN passport_stamp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passport_stamp_passport_stamp_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.ranking (
    ranking_id bigint NOT NULL,
    district character varying(50),
    like_count integer NOT NULL,
    rank integer NOT NULL,
    updated_at timestamp(6) without time zone,
    week_start_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    ranking_position integer NOT NULL,
    score integer NOT NULL,
    CONSTRAINT ranking_district_check CHECK (((district)::text = ANY ((ARRAY['JONGNO'::character varying, 'JUNG'::character varying, 'YONGSAN'::character varying, 'SEONGDONG'::character varying, 'GWANGJIN'::character varying, 'DONGDAEMUN'::character varying, 'JUNGNANG'::character varying, 'SEONGBUK'::character varying, 'GANGBUK'::character varying, 'DOBONG'::character varying, 'NOWON'::character varying, 'EUNPYEONG'::character varying, 'SEODAEMUN'::character varying, 'MAPO'::character varying, 'YANGCHEON'::character varying, 'GANGSEO'::character varying, 'GURO'::character varying, 'GEUMCHEON'::character varying, 'YEONGDEUNGPO'::character varying, 'DONGJAK'::character varying, 'GWANAK'::character varying, 'SEOCHO'::character varying, 'GANGNAM'::character varying, 'SONGPA'::character varying, 'GANGDONG'::character varying, 'SUWON'::character varying, 'SEONGNAM'::character varying, 'GOYANG'::character varying, 'YONGIN'::character varying, 'BUCHEON'::character varying, 'ANSAN'::character varying, 'ANYANG'::character varying, 'NAMYANGJU'::character varying, 'HWASEONG'::character varying, 'PYEONGTAEK'::character varying, 'UIJEONGBU'::character varying, 'SIHEUNG'::character varying, 'PAJU'::character varying, 'GIMPO'::character varying, 'GWANGMYEONG'::character varying, 'GWANGJU_GG'::character varying, 'GUNPO'::character varying, 'HANAM'::character varying, 'OSAN'::character varying, 'ICHEON'::character varying, 'YANGJU'::character varying, 'ANSEONG'::character varying, 'GURI'::character varying, 'POCHEON'::character varying, 'UIWANG'::character varying, 'YEOJU'::character varying, 'DONGDUCHEON'::character varying, 'GAPYEONG'::character varying, 'YANGPYEONG'::character varying, 'YEONCHEON'::character varying, 'GWACHEON'::character varying])::text[])))
);

ALTER TABLE public.ranking ALTER COLUMN ranking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ranking_ranking_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.scrap (
    scrap_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    passport_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.scrap ALTER COLUMN scrap_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scrap_scrap_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.team (
    team_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    team_code character varying(50) NOT NULL,
    team_name character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    invite_code character varying(50) NOT NULL  -- 미사용 컬럼, V3에서 제거 예정
);

ALTER TABLE public.team ALTER COLUMN team_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_team_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.team_member (
    teammember_id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    role character varying(255) NOT NULL,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT team_member_role_check CHECK (((role)::text = ANY ((ARRAY['LEADER'::character varying, 'MEMBER'::character varying])::text[])))
);

ALTER TABLE public.team_member ALTER COLUMN teammember_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_member_teammember_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    current_mode character varying(255),
    email character varying(50),
    nickname character varying(50) NOT NULL,
    profile_img text,
    updated_at timestamp(6) without time zone,
    friend_code character varying(8) NOT NULL,
    bio text,
    location character varying(100),
    CONSTRAINT users_current_mode_check CHECK (((current_mode)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'TEAM'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Primary Keys
--

ALTER TABLE ONLY public.auth ADD CONSTRAINT auth_pkey PRIMARY KEY (auth_id);
ALTER TABLE ONLY public.district_cover ADD CONSTRAINT district_cover_pkey PRIMARY KEY (cover_id);
ALTER TABLE ONLY public.friend ADD CONSTRAINT friend_pkey PRIMARY KEY (friend_id);
ALTER TABLE ONLY public.likes ADD CONSTRAINT likes_pkey PRIMARY KEY (like_id);
ALTER TABLE ONLY public.passport_image ADD CONSTRAINT passport_image_pkey PRIMARY KEY (passport_image_id);
ALTER TABLE ONLY public.passport ADD CONSTRAINT passport_pkey PRIMARY KEY (passport_id);
ALTER TABLE ONLY public.passport_stamp ADD CONSTRAINT passport_stamp_pkey PRIMARY KEY (passport_stamp_id);
ALTER TABLE ONLY public.ranking ADD CONSTRAINT ranking_pkey PRIMARY KEY (ranking_id);
ALTER TABLE ONLY public.scrap ADD CONSTRAINT scrap_pkey PRIMARY KEY (scrap_id);
ALTER TABLE ONLY public.team_member ADD CONSTRAINT team_member_pkey PRIMARY KEY (teammember_id);
ALTER TABLE ONLY public.team ADD CONSTRAINT team_pkey PRIMARY KEY (team_id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

--
-- Unique Constraints
--

ALTER TABLE ONLY public.district_cover ADD CONSTRAINT uk_district_cover_user_district UNIQUE (user_id, district_category);
ALTER TABLE ONLY public.likes ADD CONSTRAINT uk_like_user_passport UNIQUE (user_id, passport_id);
ALTER TABLE ONLY public.passport_stamp ADD CONSTRAINT uk_passport_stamp_passport_category UNIQUE (passport_id, category);
ALTER TABLE ONLY public.passport ADD CONSTRAINT uk_passport_user_location_date UNIQUE (user_id, latitude, longitude, visited_at);
ALTER TABLE ONLY public.scrap ADD CONSTRAINT uk_scrap_user_passport UNIQUE (user_id, passport_id);
ALTER TABLE ONLY public.users ADD CONSTRAINT uk_users_friend_code UNIQUE (friend_code);
ALTER TABLE ONLY public.users ADD CONSTRAINT uk_users_nickname UNIQUE (nickname);
ALTER TABLE ONLY public.auth ADD CONSTRAINT ukjlww566pe2tcmmnqu62w6ylgs UNIQUE (social_id, social_type);
ALTER TABLE ONLY public.team ADD CONSTRAINT ukphbgds8f9viea60jw0dllvuiv UNIQUE (team_code);

--
-- Trigger
--

CREATE TRIGGER trg_passport_location BEFORE INSERT OR UPDATE ON public.passport FOR EACH ROW EXECUTE FUNCTION public.update_passport_location();

--
-- Foreign Keys
--

ALTER TABLE ONLY public.passport_image ADD CONSTRAINT fk2v26bdu2o9b5i8mv3ef8ldyv1 FOREIGN KEY (passport_id) REFERENCES public.passport(passport_id);
ALTER TABLE ONLY public.ranking ADD CONSTRAINT fk3fvvh22u2cwktrkpu73la05yp FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.friend ADD CONSTRAINT fk3t89853ilx0np8f323suufvty FOREIGN KEY (request_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.district_cover ADD CONSTRAINT fk5tnx93oul5yn1a2omidbwfcl6 FOREIGN KEY (passport_image_id) REFERENCES public.passport_image(passport_image_id);
ALTER TABLE ONLY public.scrap ADD CONSTRAINT fk6jcivlvmiwrx9hd1d7h2tkije FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.district_cover ADD CONSTRAINT fk9gi6fa8gt7hxcvl08ta7pr4ll FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.team_member ADD CONSTRAINT fk9ubp79ei4tv4crd0r9n7u5i6e FOREIGN KEY (team_id) REFERENCES public.team(team_id);
ALTER TABLE ONLY public.passport ADD CONSTRAINT fkahin9j9chp4fp7hi5lahrwpcf FOREIGN KEY (team_id) REFERENCES public.team(team_id);
ALTER TABLE ONLY public.team_member ADD CONSTRAINT fkcwlc6ivvbf5svve5fmbg71vks FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.passport ADD CONSTRAINT fkimp0xtvk5mujh4f1bkh7833vx FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.scrap ADD CONSTRAINT fklsmigjultu7jx5u3f8diygwv3 FOREIGN KEY (passport_id) REFERENCES public.passport(passport_id);
ALTER TABLE ONLY public.likes ADD CONSTRAINT fkltqvd5mqg4c0dhmt241qnfuny FOREIGN KEY (passport_id) REFERENCES public.passport(passport_id);
ALTER TABLE ONLY public.friend ADD CONSTRAINT fknbki3da2tox3pedxa9qs2gaqi FOREIGN KEY (receiver_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.likes ADD CONSTRAINT fknvx9seeqqyy71bij291pwiwrg FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.auth ADD CONSTRAINT fkpv45mvdt7km1gvrtn5f9rsvd7 FOREIGN KEY (user_id) REFERENCES public.users(user_id);
ALTER TABLE ONLY public.passport_stamp ADD CONSTRAINT fks68ubk271qdme3btnhlsf09mo FOREIGN KEY (passport_id) REFERENCES public.passport(passport_id);

--
-- PostgreSQL database dump complete
--
