-- 토스페이먼츠 일회성 결제 테이블 추가 (Issue #80)
-- > payment_id : PK
-- > order_id   : UUID 문자열 (UNIQUE) — 토스 결제창 호출 시 사용하는 주문 식별자
-- > user_id    : 결제한 사용자 (FK)
-- > amount     : 결제 금액 (KRW 원 단위 정수)
-- > status     : PENDING(주문 생성) → COMPLETED(승인 완료) / FAILED / CANCELED
-- > payment_key: 토스가 confirm 시 발급하는 결제 키. PENDING 상태에서는 NULL
-- > product_type: 상품 타입 (ProductType enum 문자열) — 가격 정책은 백엔드 enum이 단일 진실 공급원

CREATE TABLE public.payment (
    payment_id    bigint NOT NULL,
    order_id      varchar(64) NOT NULL,
    user_id       bigint NOT NULL,
    amount        bigint NOT NULL,
    status        varchar(20) NOT NULL,
    payment_key   varchar(200),
    product_type  varchar(50) NOT NULL,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    CONSTRAINT payment_status_check
        CHECK (status IN ('PENDING','COMPLETED','FAILED','CANCELED'))
);

ALTER TABLE public.payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_payment_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (payment_id);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT uk_payment_order_id UNIQUE (order_id);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);

-- 사용자별 결제 이력 조회 / 상태별 집계용
CREATE INDEX idx_payment_user_id ON public.payment (user_id);
CREATE INDEX idx_payment_status ON public.payment (status);
